default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: slow_food_online_development

test:
  <<: *default
  database: slow_food_online_test

production:
  <<: *default
  database: slow_food_online_production
  username: slow_food_online
  password: <%= ENV['SLOW_FOOD_ONLINE_DATABASE_PASSWORD'] %>
